Algoritmo "calculaDivisaoReal"
// Disciplina   : [Algoritmo e Lógica de Programação]
// Professor   : Nelio Alves
// Descrição   : Imprime apenas o valor inteiro de um número real.
// Autor(a)    : Daniel Caixeta
// Data atual  : 16/07/2023
Var

   a : real
   b : inteiro

Inicio

   a <- 5
   
   b <- Int(a)  // "Recebe" apenas a parte inteira do valor real.

   escreval(b)  // Imprime apenas a parte inteira do valor real.

Fimalgoritmo