Algoritmo "processaDados"
// Disciplina   : [Algoritmo e Lógica de Programação]
// Professor   : Nelio Alves 
// Descrição   : Práticas com processamento de dados.
// Autor(a)    : Daniel Caixeta
// Data atual  : 15/07/2023
Var

   x, y : inteiro
   w : real

Inicio

      x <- 5
      
      y <- 2 * x
      
      w <- x * (2 ^ 3)
      
      escreval("O valor de x é:", x)
      escreval("O valor de y é:", y)
      escreval("O valor de w é:", w)

Fimalgoritmo